// Central registry of error codes (sync with docs/error-codes.md)
module.exports = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_CODE: 'INVALID_CODE',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ALREADY_VERIFIED: 'ALREADY_VERIFIED',
  BIKE_INVALID: 'BIKE_INVALID',
  MAX_BIKES_REACHED: 'MAX_BIKES_REACHED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  FORBIDDEN: 'FORBIDDEN',
  SERVER_ERROR: 'SERVER_ERROR'
};
