name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install backend deps
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: ESLint (strict)
        working-directory: backend
        run: npm run lint:strict

  contract-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install backend deps
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Lint OpenAPI
        working-directory: backend
        run: npx redocly lint openapi.yaml
      - name: Lint error codes
        working-directory: backend
        run: npm run lint:error-codes
      - name: Generate & verify operationIds
        working-directory: backend
        run: |
          node scripts/generateOperationIds.js
          git diff --quiet types/operation-ids.d.ts || (echo 'operation-ids.d.ts not committed'; git --no-pager diff types/operation-ids.d.ts; exit 1)
      - name: Generate frontend API types
        run: |
          cd backend && npm run gen:types || true
          git diff --quiet frontend/src/api/generated/schema.d.ts || (echo 'Generated schema.d.ts differs; please commit.'; git --no-pager diff frontend/src/api/generated/schema.d.ts; exit 1)
      - name: Contract tests
        working-directory: backend
        env:
          CONTRACT_ONLY: 1
          SKIP_DB: 1
        run: npm run test:contract

  full-tests:
    needs: contract-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install backend deps
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Unit+integration tests (coverage enforced)
        working-directory: backend
        env:
          SKIP_DB: 1
        run: npm run test:ci -- --coverage --coverageReporters=text-summary --coverageReporters=lcov
      - name: Show coverage summary
        run: |
          if [ -f backend/coverage/lcov.info ]; then grep -E '^SF:' backend/coverage/lcov.info | wc -l || true; fi
      - name: Upload coverage to Codecov (backend)
        uses: codecov/codecov-action@v4
        with:
          files: backend/coverage/lcov.info
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
          verbose: true
      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
          if-no-files-found: error
      - name: Health script syntax check
        run: node -c scripts/healthCheck.js || true
      - name: Diff coverage gate (backend)
        run: |
          node backend/scripts/diffCoverage.js --threshold 80 || (echo 'Diff coverage below threshold' && exit 1)

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install frontend deps
        run: |
          cd frontend && npm install
      - name: Frontend tests
        run: |
          cd frontend && npm run test -- --coverage --reporter=default
        env:
          CI: true
      - name: Upload coverage to Codecov (frontend)
        uses: codecov/codecov-action@v4
        with:
          files: frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false
          verbose: true
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
          if-no-files-found: warn

  health-check:
    runs-on: ubuntu-latest
    needs: full-tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: |
          npm install
          cd backend && npm install
      - name: Start backend (no DB)
        run: |
          SKIP_DB=1 PORT=5001 node backend/index.js &
          echo $! > backend_server.pid
      - name: Wait for server
        run: |
          n=0
          until [ $n -ge 25 ]; do
            curl -fsS http://localhost:5001/api/health/health && break
            n=$((n+1))
            sleep 0.4
          done
      - name: Run health script
        run: node scripts/healthCheck.js
      - name: Stop server
        run: |
          kill $(cat backend_server.pid) || true

  docker-build:
    runs-on: ubuntu-latest
    needs: full-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -t serviskol-backend:ci ./backend
      - name: Build frontend image
        run: docker build -t serviskol-frontend:ci ./frontend

  compose-smoke:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose up
        run: |
          docker compose up -d --build
          sleep 8
          curl -f http://localhost:5001/api/health/health
          curl -f http://localhost:8080/health || echo 'frontend health not configured'
          # verify metrics endpoint returns 200 and contains cyklo_http_requests_total
          curl -f http://localhost:5001/api/metrics | grep -q 'cyklo_http_requests_total' || (echo 'metrics missing'; exit 1)
          # ověření nových metrik
          curl -f http://localhost:5001/api/metrics | grep -q 'cyklo_apdex_total' || (echo 'apdex metric missing'; exit 1)
          curl -f http://localhost:5001/api/metrics | grep -q 'cyklo_http_status_class_total' || (echo 'status class metric missing'; exit 1)
      - name: Logs (backend)
        if: failure()
        run: docker logs serviskol-backend || true
      - name: Logs (frontend)
        if: failure()
        run: docker logs serviskol-frontend || true
      - name: Compose down
        run: docker compose down -v

  e2e-playwright:
    runs-on: ubuntu-latest
    needs: compose-smoke
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps (with Playwright)
        working-directory: frontend
        run: |
          npm ci || npm install
          npx playwright install --with-deps
      - name: Start stack
        run: |
          ENABLE_TEST_UTILS=1 docker compose up -d --build
          n=0
          until curl -fsS http://localhost:5001/api/health/health; do sleep 1; n=$((n+1)); [ $n -gt 40 ] && exit 1; done
          until curl -fsS http://localhost:8080/; do sleep 1; n=$((n+1)); [ $n -gt 60 ] && exit 1; done
      - name: Run Playwright tests
        working-directory: frontend
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:8080
        run: npm run test:e2e
      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: frontend/test-results
      - name: Stop stack
        if: always()
        run: docker compose down -v

  security-audit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: backend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Install frontend deps
        working-directory: frontend
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Backend npm audit (prod)
        working-directory: backend
        run: npm audit --omit=dev || true
      - name: Frontend npm audit (prod)
        working-directory: frontend
        run: npm audit --omit=dev || true
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  release:
    runs-on: ubuntu-latest
    needs: [full-tests, frontend, compose-smoke, e2e-playwright, security-audit]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root dev deps
        run: |
          npm install --no-audit --no-fund
          cd backend && npm install --no-audit --no-fund
          cd ../frontend && npm install --no-audit --no-fund
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
